name: Flutter

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.22.2'
      - name: Install packages
        run: flutter pub get
      - name: Linter
        run: flutter analyze
      # - name: Test
      #   run: flutter test
